# Generated by Django 3.1.7 on 2022-01-24 16:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stake', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stake',
            name='due_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='stake',
            name='returns',
            field=models.IntegerField(default=0),
        ),
    ]
