# Generated by Django 3.1.7 on 2022-01-25 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stake', '0002_auto_20220124_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='stake',
            name='closed_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stake',
            name='request_payment_status',
            field=models.BooleanField(default=False),
        ),
    ]
