# Generated by Django 3.1.7 on 2022-01-25 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stake', '0003_auto_20220125_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='stake',
            name='payment_hash',
            field=models.CharField(default='none', max_length=50),
        ),
    ]
