# Generated by Django 3.1.7 on 2022-01-25 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stake', '0004_stake_payment_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stake',
            name='amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='stake',
            name='returns',
            field=models.FloatField(default=0),
        ),
    ]
